# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: sds-ngix-svc-jhub
version: 0.0.1-set.by.chartpress
appVersion: "4.0.2"
description: JupyterHub for SDS 
type: application 
#keywords: [jupyter, jupyterhub, z2jh]
home: https://z2jh.jupyter.org
sources: [C:\Users\jgupta\git-sds\helm-jhub\jupyterhub]
icon: https://hub.jupyter.org/helm-chart/images/hublogo.svg
kubeVersion: ">=1.23.0-0"
maintainers:
  # Since it is a requirement of Artifact Hub to have specific maintainers
  # listed, we have added some below, but in practice the entire JupyterHub team
  # contributes to the maintenance of this Helm chart.
  - name: Erik Sundell
    email: erik@sundellopensource.se
  - name: Simon Li
    url: https://github.com/manics/
annotations:
  intersystems/sds-title: Jupyter SDS Service
  intersystems/sds-organization: InterSystems Corporation
  intersystems/sds-category: custom

